#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'


#a

cookbook "apt"

#b

cookbook "build-essential", "1.4.4"

#c

cookbook 'chef-client'
cookbook "cron"

#d

cookbook 'drush',
  :git => 'https://github.com/goruha/chef-drush.git',
  :ref => 'add_alias_provider'

#e

#f


#g


#h


#i


#j


#k

#l

#m

cookbook "mysql", "4.0.10"
cookbook "memcached",
  :git => 'https://github.com/opscode-cookbooks/memcached.git',
  :ref => 'master'

#n

cookbook "nano"
cookbook "nginx"

#o

#cookbook "openssl"


#p

#cookbook 'platform_packages',
#  :git => 'git://github.com/fnichol/chef-platform_packages.git',
#  :ref => 'master'

cookbook "php"
cookbook "php-fpm"
#q

#r

#s


#t

#u


#v

#cookbook "vim"

#w

#x

#y

#z

